### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by babakness** [Rich-Harris/ramjet#34]
Any chance this will work with certain CSS transformations like rotate, i.e.:

```css
#a{
  ...
}

#b{
  ...
  transform: rotate(90deg);
}
```

Also, rotating twice from beginning to end on something like

 ```css
#b{
  ...
  transform: rotate(720deg);
}
``` 

would be super cool!
